INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('F. C. Barcelona', 'Barcelona');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Burgos CF', 'Burgos');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('U. D. Las Palmas', 'Las Palmas');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Athletic Club', 'Ath. Bilbao');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Real Betis Balompié', 'Betis');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('R. C. Deportivo de La Coruña', 'Dptivo. Coruña');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('RCD Espanyol', 'Espanyol');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Real Oviedo', 'Oviedo');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Real Madrid C. F.', 'Real Madrid');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Real Sociedad', 'Real Sociedad');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Valencia C. F.', 'Valencia');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Real Zaragoza', 'Zaragoza');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Cádiz C. F.', 'Cádiz');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Córdoba C. F.', 'Córdoba');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Elche C. F.', 'Elche');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('R. C. D. Mallorca', 'Mallorca');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('C. A. Osasuna', 'Osasuna');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('UE Sant Andreu', 'Sant Andreu');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Sevilla FC', 'Sevilla');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Hércules C. F.', 'Hércules');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('EDF Logroño', 'Logroñés');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Real Murcia C. F.', 'Murcia');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('CE Sabadell FC', 'Sabadell');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('C. D. Tenerife', 'Tenerife');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Levante U. D.', 'Levante');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Deportivo Alavés', 'Alavés');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('R. C. Recreativo de Huelva', 'Rec. Huelva');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Terrassa Olímpica 2010', 'Terrassa');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('CD Puertollano', 'Calvo Sotelo');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Real Jaén CF', 'Jaén');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Getafe C. F.', 'Getafe');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Racing Club de Ferrol', 'Ferrol');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Algeciras CF', 'Algeciras');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Real Madrid Club de Fútbol Castilla', 'Real Madrid B');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Bilbao Athletic', 'Ath. Bilbao B');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Albacete Balompié', 'Albacete');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('UE Figueres', 'Figueres');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('S. D. Eibar', 'Éibar');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Palamós CF', 'Palamós');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('A. D. Mérida', 'Mérida');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('C. D. Badajoz', 'Badajoz');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('C. D. Lugo', 'Lugo');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('CD Leganés', 'Leganés');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Extremadura UD', 'Extremadura');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('CD Numancia', 'Numancia');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Málaga C. F.', 'Málaga');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('SD Ponferradina', 'Ponferradina');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('SD Huesca', 'Huesca');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Girona FC', 'Girona');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Real Unión Club', 'Real Unión');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('F. C. Cartagena', 'Cartagena');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('AD Alcorcón', 'Alcorcón');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('CD Guadalajara', 'Guadalajara');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('CD Marino', 'Club Deportivo Marino');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('UP Langreo', 'Unión Popular de Langreo');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Caudal Deportivo', 'Caudal Deportivo');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('RC Portuense', 'Racing Club Portuense');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('UCAM Murcia Club de Fútbol', 'UCAM Murcia Club de Fútbol');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('RCD Carabanchel', 'Real Club Deportivo Axpo Carabanchel');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('U. D. Logroñés', 'Unión Deportiva Logroñés');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('CD Izarra', 'Club Deportivo Izarra');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Club de Fútbol Badalona', 'Club de Fútbol Badalona');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Club Marino de Luanco', 'Club Marino de Luanco');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Montilla CF', 'Montilla Club de Fútbol');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('Sporting de Gijón', 'Real Sporting de Gijón');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('CE Europa', 'Club Esportiu Europa');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('CP Cacereño', 'Club Polideportivo Cacereño');
INSERT INTO Otro_nombre (nom_otro, nom_corto_o) VALUES ('SD Tenisca', 'Sociedad Deportiva Tenisca');
