INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Wanda Metropolitano', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Camp Nou', 1957, 99354);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de El Plantío', 1964, 12642);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nuevo Castalia', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Balaídos', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Miguel Prieto', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Gran Canaria', 2003, 32392);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Requexón', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('San Mamés', 2013, 53331);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Benito Villamarín', 1929, 60721);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Abanca-Riazor', 1944, 32490);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('RCDE Stadium', 2009, 40500);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal Carlos Tartiere', 2000, 30500);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Santiago Bernabéu', 1947, 81044);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Reale Arena', 1993, 39313);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Mestalla', 1923, 49430);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('La Romareda', 1957, 33608);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nuevo Lasesarre', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Ramón de Carranza', 1957, 20000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nuevo Arcángel', 1993, 20989);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Martínez Valero', 1976, 31388);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Son Moix', 1999, 23142);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Sadar', 1967, 23516);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Narcís Sala', 1970, 6593);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Ramón Sánchez-Pizjuán', 1958, 43883);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Paterna', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('José Zorrilla', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal Reino de León', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nou Estadi', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('José Rico Pérez', 1974, 29500);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Las Gaunas', 2002, 16000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Enrique Roca de Murcia', 2006, 31179);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Pasarón', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Sardinero', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Campo de Fútbol de Vallecas', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nova Creu Alta', 1967, 11908);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Heliodoro Rodríguez López', 1925, 22824);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de La Línea', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Ciudad de Valencia', 1969, 26354);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Pistas del Helmántico', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Mendizorroza', 1924, 19840);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nuevo Colombino', 2001, 21670);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Olímpic de Terrassa', 1960, 11500);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Ciudad de Puertollano', 2010, 6813);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('La Victoria', 2001, 12569);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Coliseum Alfonso Pérez', 1998, 16500);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('A Malata', 1993, 12043);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nuevo Mirador', 1999, 7200);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Alfredo Di Stéfano', 2005, 6000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal Alfonso Murube', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Cerro del Espino', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Cartagonova', 1988, 14353);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Chapín', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Instalaciones de Lezama', 1971, 3200);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Carlos Belmonte', 1960, 18000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Las Llanas', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Vilatenim', 1986, 9000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Camp dEsports', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Pallafría', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Ipurúa', 1947, 8164);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nou Estadi de Palamós', 1989, 3652);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Suárez Puerta', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Multiusos de San Lázaro', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Romano', 1953, 14600);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Madrigal', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nuevo Vivero', 1998, 14175);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Anxo Carro', 1974, 7840);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Butarque', 1998, 12454);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Francisco de la Hera', 1996, 12000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Juegos Mediterráneos', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nuevo Los Pajaritos', 1999, 8261);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Campo de Son Malferit', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('La Rosaleda', 1941, 30044);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nuevo Los Cármenes', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Toralín', 2000, 8400);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Jesús Navas', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Alcoraz', 1972, 9100);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Montilivi', 1970, 11200);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Stadium Gal', 1926, 5000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Santo Domingo', 1978, 5100);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Collao', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Pedro Escartín', 1967, 7000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Anduva', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Anexos Santo Domingo', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Antonio Domínguez', 1992, 7500);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Artunduaga', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Berazubi', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Camp de la Morera', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Campo de fútbol Luis Oliver', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Campo de Serralta', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Campo Municipal de Garachico', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Centro Deportivo Calavera', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Centro Deportivo Vega de Triana', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Ciudad Deportiva de Getafe', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Astobiza', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Bayu', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Fornás', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Malecón', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Mundo del Fútbol', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('El Rosal', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Estadi Municipal de Capellades', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Estadio Francisco Gil Cardona', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Estadio La Devesa', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Estadio Municipal de Deportes El Mazo', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Estadio Vivar Téllez', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Etxezuri', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Ganzábal', 1922, 4024);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Gobela', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Hermanos Antuña', 1951, 4000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Hermanos Llana', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Instalaciones de Zubieta', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('José del Cuvillo', 1972, 8600);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('La Condomina', 1924, 4600);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('La Cueva', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('La Florida', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('La Mina', 1916, 2000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('La Veigona', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Las Callejas', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Las Tolvas', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Mallona', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Manuel Galeano Sánchez', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Merkatondoa', 1928, 3500);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Mintxeta', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Badalona', 2017, 4170);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de La Salud', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Loinaz', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Miramar', 1952, 5000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Montilla', 1981, 5000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal de Villafranca', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal El Molino', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal El Molinón-Enrique Castro Quini', 1908, 30000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Municipal Les Grases', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nou Sardenya', 1995, 4000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nuevo Ategorri', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Nuevo Pepico Amat', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Príncipe Felipe', 1977, 7000);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Silvestre Carrillo', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Tabira', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Urbieta', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Urritxe', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Valle las Huertas', NULL, NULL);
INSERT INTO Estadio (nom_estad, fecha_inaug, capacidad) VALUES ('Virgen de las Nieves', 2001, 6000);
