INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Christopher Columbus: The Discovery', 1992, '1492: Conquest of Paradise',1992, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('1919, crónica del alba', 1983, 'Valentina',1982, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Genesis', 1998, 'Aftermath',1994, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Brácula. Condemor II', 1997, 'Aquí llega Condemor, el pecador de la pradera',1996, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Avisa a Curro Jiménez', 1978, 'Curro Jiménez',1976, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El regreso de una leyenda', 1995, 'Avisa a Curro Jiménez',1978, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Carmen', 1983, 'Bodas de sangre',1981, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El amor brujo', 1986, 'Bodas de sangre',1981, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Idioterne', 1998, 'Breaking the Waves',1996, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Carmen nue', 1984, 'Carmen',1983, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El amor brujo', 1986, 'Carmen',1983, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('1492: Conquest of Paradise', 1992, 'Christopher Columbus: The Discovery',1992, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Después de tantos años', 1994, 'El desencanto',1976, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Don Quijote de Orson Welles', 1992, 'El Quijote de Miguel de Cervantes',1991, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Don Quijote de Orson Welles', 1992, 'Tskhovreba Don Kikhotisa da Sancho Panchosi',1988, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El aullido del diablo', 1987, 'El retorno del Hombre-Lobo',1981, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El aullido del diablo', 1987, 'La bestia y la espada mágica',1983, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El aullido del diablo', 1987, 'La maldición de la bestia',1975, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El crack II', 1983, 'El crack',1981, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El cura ya tiene hijo', 1984, 'El hijo del cura',1982, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El libro de buen amor II', 1976, 'El libro de buen amor',1975, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El Lute II: mañana seré libre', 1988, 'El Lute (camina o revienta)',1987, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El pico 2', 1984, 'El pico',1983, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El regreso de Eva Man', 1982, 'Eva man (Due sessi in uno)',1980, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El regreso del viento del Norte', 1994, 'La leyenda del viento del Norte',1992, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('La bestia y la espada mágica', 1983, 'El retorno del Hombre-Lobo',1981, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El retorno del Hombre-Lobo', 1981, 'La maldición de la bestia',1975, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Licántropo: El asesino de la luna llena', 1996, 'El retorno del Hombre-Lobo',1981, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El tío del saco y el inspector Lobatón', 1993, 'Quién sabe dónde',1992, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El vivo retrato', 1986, 'La cigüeña bondadosa',1980, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('El último guateque II', 1988, 'El último guateque',1978, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Evilio vuelve (El purificador)', 1994, 'Evilio.',1992, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Fulanita y sus menganos', 1976, 'Yo soy Fulana de Tal',1975, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Yellow Hair and the Fortress of Gold', 1984, 'Hundra',1983, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('J.R. contraataca', 1983, 'Le llamaban J.R.',1982, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Juego sucio en Casablanca', 1985, 'Juego sucio en Panamá',1975, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Katy, Kiki y Koko', 1988, 'Katy, la oruga',1984, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Kilma, reina de las amazonas', 1977, 'La diosa salvaje',1975, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('La bestia y la espada mágica', 1983, 'La maldición de la bestia',1975, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Licántropo: El asesino de la luna llena', 1996, 'La bestia y la espada mágica',1983, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('La Celestina', 1996, 'La Celestina',1983, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Manuel y Clemente', 1986, 'La de Troya en el Palmar',1984, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Nacional III', 1982, 'La escopeta nacional',1978, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Patrimonio nacional', 1981, 'La escopeta nacional',1978, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('La segunda guerra de los niños', 1981, 'La guerra de los niños',1980, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Las locuras de Parchís', 1982, 'La guerra de los niños',1980, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Parchís entra en acción', 1983, 'La guerra de los niños',1980, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Licántropo: El asesino de la luna llena', 1996, 'La maldición de la bestia',1975, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('La regenta', 1995, 'La regenta',1975, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Las locuras de Parchís', 1982, 'La segunda guerra de los niños',1981, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Parchís entra en acción', 1983, 'La segunda guerra de los niños',1981, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('La tribu de los aurones', 1988, 'Los aurones',1986, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('La tumba de los muertos vivientes', 1983, 'Le lac des morts vivants',1981, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Las cosas del querer II', 1995, 'Las cosas del querer',1989, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Parchís entra en acción', 1983, 'Las locuras de Parchís',1982, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Ya no va más', 1988, 'Los bingueros',1979, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Los últimos golpes de El Torete', 1980, 'Perros callejeros',1977, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Los últimos golpes de El Torete', 1980, 'Perros callejeros II',1979, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('¡¡Semos peligrosos!! (uséase Makinavaja 2)', 1993, 'Makinavaja, el último choriso',1992, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Nacional III', 1982, 'Patrimonio nacional',1981, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Presence of Mind', 1999, 'Otra vuelta de tuerca',1985, 'remake');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Perros callejeros II', 1979, 'Perros callejeros',1977, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Siempre hay un camino a la derecha', 1997, 'Suspiros de España (y Portugal)',1995, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('To er mundo é... ¡demasiao!', 1985, 'To er mundo é güeno',1982, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('To er mundo é... ¡demasiao!', 1985, 'To er mundo é... mejo!',1982, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Victòria! 3: El seny i la rauxa', 1984, 'Victòria! 2: La disbauxa del 17',1983, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Victòria! 3: El seny i la rauxa', 1984, 'Victòria! La gran aventura dun poble',1983, 'secuela');
INSERT INTO pelicula_relac (titulo_obra_pr, agno_produc_pr, titulo_obra_rela_pr, agno_produc_rela_pr, tipo_pr) VALUES ('Por fin solos', 1995, '¡Por fin solos!',1994, 'secuela');
