INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('13 x 13', 1987, 'Stress de primavera', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Andalucía, un siglo de fascinación', 1996, 'El grito del sur. Casas Viejas', 1, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, '(#5.12)', 12, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Buscando un Valium desesperadamente', 4, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Buscarse la vida', 8, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Bésame, Alicia', 4, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Cara de ángel', 2, 6);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Caído del cielo', 3, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Cita a ciegas', 9, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Comunicando', 2, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Confidencias', 8, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Cosa Nostra', 2, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Deseo, pasión y paciencia', 13, 4);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'El fin del milenio', 5, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'El guateque', 6, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'El secreto del éxito', 7, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Ellos y ella', 11, 4);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Elígeme', 1, 3);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Enamorados', 8, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Esta niña es mía', 4, 4);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Esta tía es una hermana', 9, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Esto es la guerra', 12, 4);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Gimnasia y amnesia', 1, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'La quimera del oro', 13, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'La tentación vive abajo', 4, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'La visita', 11, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Lecciones íntimas', 6, 4);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Los amigos de los niños', 5, 4);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Madam Alicia', 3, 4);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Malas influencias', 1, 6);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Mamá sale todas las noches', 11, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Mamá, papá... y la novia de papá', 3, 3);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Margarita se llama mi amor', 5, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'No me maltrates', 5, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Nímeros rojos', 7, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Padre no hay más que muchos', 6, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Papeles', 2, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Pequeño tirano', 7, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Petri woman', 6, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Predicando en el desierto', 9, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Revista de tropa', 1, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Seis en un sofá', 10, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Semana de pasión', 4, 3);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Ser padres', 10, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Temor y temblor', 12, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Terapia de contacto', 13, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Una chica natural', 10, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Canguros', 1994, 'Valiente San Valentín', 3, 5);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Cicle Santiago Rusiñol', 1981, 'El senyor Josep enganya a la dona i la dona del senyor Josep falta a lhome', 2, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Cicle Santiago Rusiñol', 1981, 'Santiago Rusiñol: la vida', 4, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Coup de foudre', 1988, 'Adolphe et les menteuses', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Coup de foudre', 1988, 'Martingale', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Coup de foudre', 1988, 'Rendez-vous à Lisbonne', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Coup de foudre', 1988, 'Retour', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Dark Justice', 1991, 'Instant Replay', 9, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Dark Justice', 1991, 'Venus Flytrap', 16, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Delirios de amor', 1989, 'Párpados', 13, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Delirios de amor', 1989, 'Un instante en tu piel', 10, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Dinamo', 1985, '(1986-02-10)', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Eurocops', 1988, 'Shanghai Lilly', 1, 4);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Función de noche', 1995, 'La zapatera prodigiosa', 3, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Galeria oberta', 1985, 'Damunt lherba', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Glasnost', 1989, 'Tots els que cauen', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Gran teatre', 1980, 'Albert i Francina', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Gran teatre', 1980, 'El Cafè de la Marina', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Gran teatre', 1980, 'La nau', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Gran teatre', 1980, 'La roda de la fortuna', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Historias del otro lado', 1988, 'Mnemos', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Lletres catalanes', 1975, 'Ball robat', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Lletres catalanes', 1975, 'El Tartuf', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Lletres catalanes', 1975, 'El verí del teatre', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Lletres catalanes', 1975, 'Homes i no', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Lletres catalanes', 1975, 'La llotja', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Lletres catalanes', 1975, 'Molt soroll per no res', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Lletres catalanes', 1975, 'Revolta de bruixes', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Lletres catalanes', 1975, 'Salomé', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Lletres catalanes', 1975, 'Sílvia Ocampo', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Makinavaja', 1995, 'En el barrio sobra siensia y lo que farta se inventa', 1, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#1.1)', 1, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#1.10)', 10, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#1.2)', 2, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#1.3)', 3, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#1.4)', 4, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#1.6)', 6, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#1.8)', 8, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#1.9)', 9, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#2.16)', 16, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#2.22)', 22, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#2.4)', 4, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(#2.5)', 5, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(1997-06-12)', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(1997-06-19)', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(1997-09-25)', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(1997-10-02)', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(1997-10-23)', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(1997-11-13)', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(1997-11-20)', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(1997-11-27)', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(1997-12-11)', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '(1997-12-25)', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'A toda pastilla', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Acusado', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Al pan, pan', 8, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Borriquito como tú', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Bésame mucho', 13, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Castillos en el aire', 1, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Cincuenta tacos', 2, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Con nueve basta', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Cosas de críos', 20, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Cría cuervos', 23, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Dime que me quieres', 14, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'El hombre del traje gris', 1, 3);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'El niño del Pellizquito', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'El que se fue a Sevilla', 12, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Expediente F', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Fuimos novios', 11, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Haciendo trampas', 5, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Hogar, dulce hogar', 6, 3);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'La abuela cumple 80 años', 4, 3);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'La guerra del taxi', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'La sombra de una duda', 10, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'La vida sigue igual', 6, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'La última carrera', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Las chicas son guerreras', 9, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Llamando a las puertas del cielo', 17, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Los niños no vienen de París', 19, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Madre no hay más que dos', 3, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Pareja de ases', 3, 3);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Rebelde con causa', 7, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Regalo de pedida', 2, 3);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Sin perdón', 21, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Sucedió una noche', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Tres meses y un día', 7, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Tres no son multitud', 11, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Un tranvía llamado deseo', 18, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Y se armó el Belén', 15, 2);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, 'Ya está aquí, ya llegó', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '¡Fuego!', 5, 3);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Menudo es mi padre', 1996, '¡Qué noche la de aquel fin de año!', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Nova ficció', 1996, 'Més fort que la vida mateixa', 7, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Novel·la', 1979, 'Elisabeth i Maria', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Pepe Carvalho', 1999, 'Alla ricerca di Sheherazade', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Pepe Carvalho', 1999, 'El hermano pequeño', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Pepe Carvalho', 1999, 'Il centravanti è stato assassinato verso sera', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Pepe Carvalho', 1999, 'La solitude du manager', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Pepe Carvalho', 1999, 'Padre, patrón', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Pepe Carvalho', 1999, 'Tal como éramos', NULL, NULL);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Serie negra', 1994, 'La sombra del delator', 3, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Sonatas', 1983, 'Sonata de primavera', 1, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Teta', 1987, 'Das Automobil', 6, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Teta', 1987, 'Der Salonlöwe', 5, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Teta', 1987, 'Die Braut', 3, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Teta', 1987, 'Die Geburt', 1, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Teta', 1987, 'Die Hochzeit', 7, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Teta', 1987, 'Die Renovierung', 2, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('Teta', 1987, 'Die Wiege', 4, 1);
INSERT INTO Capitulo (titulo_obra_c, agno_produc_c, titulo_cap, num_cap, num_temp) VALUES ('¡Qué grande es el teatro!', 1999, 'La opinión de Amy', NULL, NULL);
